In [1]:
import pandas as pd
import json

In [54]:
df = pd.read_csv("../data/preprocessed/colex_pron_langs.csv", sep="\t", index_col=0)

In [55]:
df = df.reset_index(drop=True)

In [56]:
df["lemma_lang"] = df["SENSE_LEMMA"] + "_" +df["LANG_PRON"]

In [57]:
df

,SENSE_LEMMA,LANG,SYNSET1,SYNSET2,C1,C2,Conc.M.1,Conc.M.2,lang,LANG_PRON,LANG_NAME,lemma_lang
0,tubercule,FR,abscess#n#1,potato#n#1,abscess,potato,4.48,4.85,fr,fra,French,tubercule_fra
1,tubercule,FR,abscess#n#1,tumor#n#1,abscess,tumor,4.48,4.56,fr,fra,French,tubercule_fra
2,tubercule,FR,abscess#n#1,nodule#n#2,abscess,nodule,4.48,3.62,fr,fra,French,tubercule_fra
3,tubercule,FR,potato#n#1,tumor#n#1,potato,tumor,4.85,4.56,fr,fra,French,tubercule_fra
4,tubercule,FR,nodule#n#2,potato#n#1,nodule,potato,3.62,4.85,fr,fra,French,tubercule_fra
...,...,...,...,...,...,...,...,...,...,...,...,...
4191763,jettison,EN,jettison#v#1,jettison#v#2,jettison,jettison,3.07,3.07,en,eng,English,jettison_eng
4191764,hacer_jogging,ES,jog#v#3,jog#v#5,jog,jog,3.63,3.63,es,spa,Spanish; Castilian,hacer_jogging_spa
4191765,menyesak-nyesak,MS,jostle#v#1,jostle#v#2,jostle,jostle,3.45,3.45,ms,msa,Malay (macrolanguage),menyesak-nyesak_msa
4191766,قام_برحلة,AR,travel#v#2,travel#v#4,travel,travel,3.67,3.67,ar,ara,Arabic,قام_برحلة_ara
4191767,menyidangkan,ID,judge#v#1,pronounce#v#2,judge,pronounce,3.75,2.63,id,ind,Indonesian,menyidangkan_ind

In [58]:
pron_folder = "../data/phon/preprocessed"

In [59]:
import glob, os

In [60]:
lemma_dict = {}
for file in glob.glob(f"{pron_folder}/*.tsv"):
    print(file)
    lang = os.path.basename(file).replace(".tsv", "")
    df_pron = pd.read_csv(file, sep="\t")
    
    for lemma, pron in zip(df_pron["lemma"], df_pron["pron"]):
        lemma_dict[lemma+"_"+lang]=pron
        # df.loc[(df["SENSE_LEMMA"]==lemma) & (df["LANG_PRON"]==lang), "PRON"]=pron

../data/phon/preprocessed/nno.tsv
../data/phon/preprocessed/pjt.tsv
../data/phon/preprocessed/scn.tsv
../data/phon/preprocessed/slv.tsv
../data/phon/preprocessed/sme.tsv
../data/phon/preprocessed/stq.tsv
../data/phon/preprocessed/dlm.tsv
../data/phon/preprocessed/ces.tsv
../data/phon/preprocessed/zha.tsv
../data/phon/preprocessed/sco.tsv
../data/phon/preprocessed/ppl.tsv
../data/phon/preprocessed/nci.tsv
../data/phon/preprocessed/nav.tsv
../data/phon/preprocessed/nld.tsv
../data/phon/preprocessed/yor.tsv
../data/phon/preprocessed/lav.tsv
../data/phon/preprocessed/arz.tsv
../data/phon/preprocessed/dng.tsv
../data/phon/preprocessed/bod.tsv
../data/phon/preprocessed/khm.tsv
../data/phon/preprocessed/bak.tsv
../data/phon/preprocessed/apw.tsv
../data/phon/preprocessed/msa.tsv
../data/phon/preprocessed/fao.tsv
../data/phon/preprocessed/haw.tsv
../data/phon/preprocessed/asm.tsv
../data/phon/preprocessed/che.tsv
../data/phon/preprocessed/ceb.tsv
../data/phon/preprocessed/nya.tsv
../data/phon/preprocessed/nap.tsv
../data/phon/preprocessed/ido.tsv
../data/phon/preprocessed/dan.tsv
../data/phon/preprocessed/mkd.tsv
../data/phon/preprocessed/hye.tsv
../data/phon/preprocessed/hau.tsv
../data/phon/preprocessed/tel.tsv
../data/phon/preprocessed/kik.tsv
../data/phon/preprocessed/bul.tsv
../data/phon/preprocessed/ltg.tsv
../data/phon/preprocessed/pol.tsv
../data/phon/preprocessed/pms.tsv
../data/phon/preprocessed/ewe.tsv
../data/phon/preprocessed/lij.tsv
../data/phon/preprocessed/ron.tsv
../data/phon/preprocessed/eng.tsv
../data/phon/preprocessed/cor.tsv
../data/phon/preprocessed/hin.tsv
../data/phon/preprocessed/jpn.tsv
../data/phon/preprocessed/srd.tsv
../data/phon/preprocessed/sqi.tsv
../data/phon/preprocessed/cos.tsv
../data/phon/preprocessed/mlg.tsv
../data/phon/preprocessed/kmr.tsv
../data/phon/preprocessed/kxd.tsv
../data/phon/preprocessed/yid.tsv
../data/phon/preprocessed/ell.tsv
../data/phon/preprocessed/aze.tsv
../data/phon/preprocessed/cmn.tsv
../data/phon/preprocessed/tur.tsv
../data/phon/preprocessed/oci.tsv
../data/phon/preprocessed/xal.tsv
../data/phon/preprocessed/cop.tsv
../data/phon/preprocessed/div.tsv
../data/phon/preprocessed/deu.tsv
../data/phon/preprocessed/got.tsv
../data/phon/preprocessed/urd.tsv
../data/phon/preprocessed/pus.tsv
../data/phon/preprocessed/ton.tsv
../data/phon/preprocessed/mya.tsv
../data/phon/preprocessed/vol.tsv
../data/phon/preprocessed/amh.tsv
../data/phon/preprocessed/lim.tsv
../data/phon/preprocessed/ita.tsv
../data/phon/preprocessed/ukr.tsv
../data/phon/preprocessed/guj.tsv
../data/phon/preprocessed/mlt.tsv
../data/phon/preprocessed/fry.tsv
../data/phon/preprocessed/zul.tsv
../data/phon/preprocessed/cym.tsv
../data/phon/preprocessed/ang.tsv
../data/phon/preprocessed/tyv.tsv
../data/phon/preprocessed/fro.tsv
../data/phon/preprocessed/shn.tsv
../data/phon/preprocessed/mar.tsv
../data/phon/preprocessed/sga.tsv
../data/phon/preprocessed/mon.tsv
../data/phon/preprocessed/kat.tsv
../data/phon/preprocessed/rus.tsv
../data/phon/preprocessed/pan.tsv
../data/phon/preprocessed/eus.tsv
../data/phon/preprocessed/por.tsv
../data/phon/preprocessed/lit.tsv
../data/phon/preprocessed/kor.tsv
../data/phon/preprocessed/kan.tsv
../data/phon/preprocessed/mah.tsv
../data/phon/preprocessed/ben.tsv
../data/phon/preprocessed/gle.tsv
../data/phon/preprocessed/glg.tsv
../data/phon/preprocessed/bre.tsv
../data/phon/preprocessed/bel.tsv
../data/phon/preprocessed/kaz.tsv
../data/phon/preprocessed/enm.tsv
../data/phon/preprocessed/fra.tsv
../data/phon/preprocessed/srn.tsv
../data/phon/preprocessed/olo.tsv
../data/phon/preprocessed/abk.tsv
../data/phon/preprocessed/hrx.tsv
../data/phon/preprocessed/kal.tsv
../data/phon/preprocessed/liv.tsv
../data/phon/preprocessed/new.tsv
../data/phon/preprocessed/nds.tsv
../data/phon/preprocessed/ina.tsv
../data/phon/preprocessed/kbd.tsv
../data/phon/preprocessed/dsb.tsv
../data/phon/preprocessed/heb.tsv
../data/phon/preprocessed/fin.tsv
../data/phon/preprocessed/frr.tsv
../data/phon/preprocessed/tam.tsv
../data/phon/preprocessed/ind.tsv
../data/phon/preprocessed/nep.tsv
../data/phon/preprocessed/gla.tsv
../data/phon/preprocessed/glv.tsv
../data/phon/preprocessed/tuk.tsv
../data/phon/preprocessed/spa.tsv
../data/phon/preprocessed/mal.tsv
../data/phon/preprocessed/mnc.tsv
../data/phon/preprocessed/ilo.tsv
../data/phon/preprocessed/krl.tsv
../data/phon/preprocessed/bcl.tsv
../data/phon/preprocessed/khb.tsv
../data/phon/preprocessed/ast.tsv
../data/phon/preprocessed/mdf.tsv
../data/phon/preprocessed/ori.tsv
../data/phon/preprocessed/san.tsv
../data/phon/preprocessed/rgn.tsv
../data/phon/preprocessed/kir.tsv
../data/phon/preprocessed/mic.tsv
../data/phon/preprocessed/slk.tsv
../data/phon/preprocessed/sce.tsv
../data/phon/preprocessed/tgk.tsv
../data/phon/preprocessed/grc.tsv
../data/phon/preprocessed/pdc.tsv
../data/phon/preprocessed/isl.tsv
../data/phon/preprocessed/ara.tsv
../data/phon/preprocessed/hbs.tsv
../data/phon/preprocessed/swe.tsv
../data/phon/preprocessed/afr.tsv
../data/phon/preprocessed/dzo.tsv
../data/phon/preprocessed/tha.tsv
../data/phon/preprocessed/sah.tsv
../data/phon/preprocessed/lmo.tsv
../data/phon/preprocessed/ltz.tsv
../data/phon/preprocessed/nor.tsv
../data/phon/preprocessed/tgl.tsv
../data/phon/preprocessed/ckb.tsv
../data/phon/preprocessed/syl.tsv
../data/phon/preprocessed/vie.tsv
../data/phon/preprocessed/fas.tsv
../data/phon/preprocessed/ady.tsv
../data/phon/preprocessed/xho.tsv
../data/phon/preprocessed/hun.tsv
../data/phon/preprocessed/lao.tsv
../data/phon/preprocessed/epo.tsv
../data/phon/preprocessed/est.tsv

In [61]:
len(lemma_dict)

151714

In [62]:
from pandarallel import pandarallel

pandarallel.initialize(progress_bar=True)

INFO: Pandarallel will run on 10 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.

In [63]:
import numpy as np

In [64]:
df["PRON"] = df["lemma_lang"].apply(lambda x: lemma_dict.get(x, np.NaN))

In [65]:
len(df)

4191768

In [66]:
df_langs = pd.read_csv("../data/geo/languages.csv")

In [67]:
df_langs

,ID,Name,Macroarea,Latitude,Longitude,Glottocode,ISO639P3code
0,CEWA,Cewa,NaN,-14.00,34.00,nyan1308,nya
1,GIKUYU,Gikuyu,NaN,-0.75,36.75,kiku1240,kik
2,MPONDOMISE,Mpondomise,NaN,-32.00,27.00,xhos1239,xho
3,NGONI_2,Ngoni 2,NaN,-30.00,30.00,zulu1248,zul
4,OKA,Oka,NaN,7.95,5.68,yoru1245,yor
...,...,...,...,...,...,...,...
164,MICMAC,Micmac,NaN,45.00,-63.00,mikm1235,mic
165,CLASSICAL_NAHUATL,Classical Nahuatl,NaN,19.42,-99.12,clas1250,nci
166,PIPIL,Pipil,NaN,13.83,-89.58,pipi1250,ppl
167,SRANAN_TONGO,Sranan Tongo,NaN,5.83,-55.33,sran1240,srn
168,ESPERANTO,Esperanto,NaN,53.08,23.09,espe1235,epo

In [72]:
df_langs

,ID,Name,Macroarea,Latitude,Longitude,Glottocode,ISO639P3code
0,CEWA,Cewa,NaN,-14.00,34.00,nyan1308,nya
1,GIKUYU,Gikuyu,NaN,-0.75,36.75,kiku1240,kik
2,MPONDOMISE,Mpondomise,NaN,-32.00,27.00,xhos1239,xho
3,NGONI_2,Ngoni 2,NaN,-30.00,30.00,zulu1248,zul
4,OKA,Oka,NaN,7.95,5.68,yoru1245,yor
...,...,...,...,...,...,...,...
164,MICMAC,Micmac,NaN,45.00,-63.00,mikm1235,mic
165,CLASSICAL_NAHUATL,Classical Nahuatl,NaN,19.42,-99.12,clas1250,nci
166,PIPIL,Pipil,NaN,13.83,-89.58,pipi1250,ppl
167,SRANAN_TONGO,Sranan Tongo,NaN,5.83,-55.33,sran1240,srn
168,ESPERANTO,Esperanto,NaN,53.08,23.09,espe1235,epo

In [68]:
lang_lat = {}
lang_long = {}

for lang, lat, long in zip(df_langs["ISO639P3code"], df_langs["Latitude"], df_langs["Longitude"]):
    lang_lat[lang]=lat
    lang_long[lang] = long

In [69]:
df["Latitude"]=df["LANG_PRON"].apply(lambda x :lang_lat.get(x, np.NaN))
df["Longitude"]=df["LANG_PRON"].apply(lambda x :lang_lat.get(x, np.NaN))

In [70]:
df

,SENSE_LEMMA,LANG,SYNSET1,SYNSET2,C1,C2,Conc.M.1,Conc.M.2,lang,LANG_PRON,LANG_NAME,lemma_lang,PRON,Latitude,Longitude
0,tubercule,FR,abscess#n#1,potato#n#1,abscess,potato,4.48,4.85,fr,fra,French,tubercule_fra,NaN,48.0,48.0
1,tubercule,FR,abscess#n#1,tumor#n#1,abscess,tumor,4.48,4.56,fr,fra,French,tubercule_fra,NaN,48.0,48.0
2,tubercule,FR,abscess#n#1,nodule#n#2,abscess,nodule,4.48,3.62,fr,fra,French,tubercule_fra,NaN,48.0,48.0
3,tubercule,FR,potato#n#1,tumor#n#1,potato,tumor,4.85,4.56,fr,fra,French,tubercule_fra,NaN,48.0,48.0
4,tubercule,FR,nodule#n#2,potato#n#1,nodule,potato,3.62,4.85,fr,fra,French,tubercule_fra,NaN,48.0,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4191763,jettison,EN,jettison#v#1,jettison#v#2,jettison,jettison,3.07,3.07,en,eng,English,jettison_eng,d͡ʒ ɛ ɾ ɪ s n̩,52.0,52.0
4191764,hacer_jogging,ES,jog#v#3,jog#v#5,jog,jog,3.63,3.63,es,spa,Spanish; Castilian,hacer_jogging_spa,NaN,40.0,40.0
4191765,menyesak-nyesak,MS,jostle#v#1,jostle#v#2,jostle,jostle,3.45,3.45,ms,msa,Malay (macrolanguage),menyesak-nyesak_msa,NaN,NaN,NaN
4191766,قام_برحلة,AR,travel#v#2,travel#v#4,travel,travel,3.67,3.67,ar,ara,Arabic,قام_برحلة_ara,NaN,NaN,NaN
4191767,menyidangkan,ID,judge#v#1,pronounce#v#2,judge,pronounce,3.75,2.63,id,ind,Indonesian,menyidangkan_ind,NaN,0.0,0.0

In [76]:
df.to_csv("../data/preprocessed/colex_pron_geo.csv", index=False)